id: P000198
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: བར་དོའི་ཐོས་གྲོལ་ཆེན་མོའི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། གྲུབ་ཐོབ་ཀརྨ་གླིང་པ་སོགས་ཀྱིས་མཛད།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  id: SHE-015
web_metadata:
  title:
    en: A Collection of Teachings on the Great Liberation through Hearing in the Bardo
    bo: བར་དོའི་ཐོས་གྲོལ་ཆེན་མོའི་ཆོས་སྐོར་ཕྱོགས་བསྒྲིགས་བཞུགས་སོ།
  collection:
    en: Shechen Tantra Series–  Book 15
    bo: ''
  author:
    en: Drubthob Karma Lingpa
    bo: གྲུབ་ཐོབ་ཀརྨ་གླིང་པ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-015
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-015.epub
  description:
    en: ''
    bo: ''
